### ISSUE TITLE
Flat UI Select doesn't support AngularJS ng-options 

### ISSUE THREAD

**Issue by summer-liu** [designmodo/Flat-UI#173]
I'm using Flat UI and AngularJS, but it seems ng-options doesn't work here.
 
    <select class="form-control"  ng-model="school" ng-options="school.name for school in schools"></select>

The html code above works in Bootstrap, but not in Flat UI.

**Comment by StefanYohansson** [comment]
Flat-UI use select2 for changes `select` style. Can you try replace in your application the jQuery select2 for [this](https://github.com/angular-ui/ui-select) angular select2 wrapper?
