### ISSUE TITLE
Changes impacting bootstrap JS

### ISSUE THREAD

**Issue by iamthestreets** [designmodo/Flat-UI#174]
Hi,

It seems that there have been some changes made to Flat-UI. I am writing my site from scratch and using the new Flat-UI, but when I include this file `flat-ui.min.js` which I did not need before it prevents the bootstrap modal from opening. It will open and the immediately close.

How can I fix this?

**Comment by lcnju** [comment]
@iamthestreets flat-ui.min.js has already include bootstrap.min.js,
delete the code <script src="../public/js/bootstrap.min.js"> and try again

**Comment by lcnju** [comment]
hi @iamthestreets 
I met the same problem, I find `flat-ui.min.js` has already included `bootstrap.min.js`. Then I delete the code `<script src="../public/js/bootstrap.min.js"></script>`

**Comment by StefanYohansson** [comment]
duplicated with #170
