### ISSUE TITLE
striped not work

### ISSUE THREAD

**Issue by robertnicjoo** [designmodo/Flat-UI#183]
hi,
class .btn-striped would not work and 'bootstrap-flat-extras.css' is not included download files.

BTW i copy and saved 'bootstrap-flat-extras.css' codes by inspect element and when i try to load 'striped' class will remove all the classes and make button and ugly shape with default appearance.

What I have to do to solve this issue?

Thanks.

**Comment by StefanYohansson** [comment]
Is this about Flat-UI Free? I can't see any `.btn-striped` in entire project.
