### ISSUE TITLE
Release 2.2.3 to bower

### ISSUE THREAD

**Issue by builtinnya** [designmodo/Flat-UI#184]
Could you release the version which contains cb1efae (pull request #171) to bower as 2.2.3 or something like that?
We are using [lpiepiora/bower-webpack-plugin](https://github.com/lpiepiora/bower-webpack-plugin) to load bower packages, which requires correct "main" field in bower.json.

**Comment by simonbengtsson** [comment]
And when you're at it, to npm as well.

**Comment by TheSachin** [comment]
+1

**Comment by StefanYohansson** [comment]
launched release 2.3.0.
