### ISSUE TITLE
Asset filtered out and will not be served: add `Rails.application.config.assets.precompile += %w( radio.png )

### ISSUE THREAD

**Issue by javadKarbasian** [designmodo/Flat-UI#187]
hi all.
when i add the gem and bundle it and modify my application.js and application.css in rails i face the error below : 
Sprockets::Rails::Helper::AssetFilteredError in Pages#home
Asset filtered out and will not be served: add `Rails.application.config.assets.precompile += %w( radio.png )
i add a lot like the error to `config/initializers/assets.rb` but i think its not the way?does anyone face that before ?

**Comment by StefanYohansson** [comment]
I think this problem isn't a Flat-UI problem, because the project doesn't have any radio.png file. Maybe you want to ask in **stackoverflow** for more visibility.
