### ISSUE TITLE
error in npm registry

### ISSUE THREAD

**Issue by khushbuparakh** [designmodo/Flat-UI#188]
error in npm registry
'flat-ui.' is not in the npm registry.

**Comment by StefanYohansson** [comment]
here it works:
```
npm install flat-ui
```

npm version: v1.4.21
node version: v0.10.25

**Comment by StefanYohansson** [comment]
@khushbuparakh any luck with this?

**Comment by khushbuparakh** [comment]
Yeah am able to solve this issue.
Installing flat-ui. 
Thanks 

Khushbu
http://khushbu.strikingly.com
Twitter: @khushbuparakh
LinkedIn: https://LinkedIn.com/in/khushbuparakh

On Mar 31, 2016 8:09 PM, snotr <notifications@github.com> wrote:

@khushbuparakh any luck with this?

**Comment by StefanYohansson** [comment]
Welcome.
