### ISSUE TITLE
Pagination is not compatible with bootstrap

### ISSUE THREAD

**Issue by jdsingh** [designmodo/Flat-UI#189]
In bootstrap `pagination` class is applied to `ul` tag where in flat ui `pagination` class is applied to `div` and then `ul` should be the child of that `div`.

Check this guide for pagination on bootstrap docs.
http://getbootstrap.com/components/#pagination

The `ul` background color is mixed up because of this difference and should be changed in [pagination.less](https://github.com/designmodo/Flat-UI/blob/master/less/modules/pagination.less) file.

**Comment by StefanYohansson** [comment]
:+1:

**Comment by victor-torres** [comment]
@StefanYohansson seems to have properly fixed it. Give a look at his pull request above.

**Comment by MonsterCritic** [comment]
Thank you! Issue fixed by @StefanYohansson.

**Comment by TheSachin** [comment]
Hi, is this issue fixed, I am still seeing the same error

**Comment by StefanYohansson** [comment]
@TheSachin this issue is fixed in master branch but Flat-UI doesn't release any version since Nov 20, 2014.
