### ISSUE TITLE
Upgrade select2 from 3.5 to 4.1

### ISSUE THREAD

**Issue by TheSachin** [designmodo/Flat-UI#208]
It has been time since select2 has been upgraded to 4.1, We should do that too.

**Comment by ejlocop** [comment]
sir, @TheSachin how did you use select2 in flat-ui? 
coz it seems that i cannot set dynamic data to select.
```javascript
$('#property_type').select2({
          placeholder: 'Select Property Type',
          data : [{ id: 0, text: 'enhancement' }, { id: 1, text: 'bug' }, { id: 2, text: 'duplicate' }, { id: 3, text: 'invalid' }, { id: 4, text: 'wontfix' }],
        });


```
// this is a sample only but it gives me this error
![image](https://cloud.githubusercontent.com/assets/12082880/12510085/2516aa70-c142-11e5-925b-6593aa39c4b9.png)

**Comment by TheSachin** [comment]
Hi, can you post HTML code?

**Comment by ejlocop** [comment]
```html
<select name="property_type" multiple='multiple' autocomplete="off" id="property_type" class="form-control">
        </select>
```

**Comment by ejlocop** [comment]
@designmodo

**Comment by kevin-brown** [comment]
Select2 is bundled with Flat UI [in the core JS files](https://github.com/designmodo/Flat-UI/blob/68ddc1d2c4f0a80d6b414d858f7d3cf037eb1e3f/Gruntfile.js#L83) instead of being split out as a vendor component. This makes it difficult to use newer versions of Select2 with Flat UI, which is causing a few problems and I keep seeing tickets related to it.

Either upgrading to 4.0.x or separating Select2 out as a vendor component would solve this issue.

**Comment by ejlocop** [comment]
thanks, but i somehow managed to solve this issue by deleting $.fn.select2 object. then import the latest version of select2 after flat-ui.js :)

**Comment by hotvic** [comment]
+1

@ejlocop That not works with v4 of select2, the markup of select2 v4 is different from select2 v3 so the css shipped with Flat-UI not styles the v4.

**Comment by StefanYohansson** [comment]
Hey guys... just to heads up, I'm working on this one. If anyone want to take a look.
https://github.com/StefanYohansson/Flat-UI/tree/feature/upgrade-select2

I have only one thing to finish this:
- multiselect

**Comment by maracuja-juice** [comment]
@StefanYohansson What has to be done for the multiselect?
