### ISSUE TITLE
FlatUI checkbox not working in Yii2

### ISSUE THREAD

**Issue by miyasita1958** [designmodo/Flat-UI#219]
I need to use FlatUI checkbox style in Yii2 :

    <div class="col-md-3">
        <?= Html::checkbox("search-name", false, ['id' => 'search-name', 'data-toggle' => 'checkbox']) ?>
        <?= Html::label("ファイル名", "search-name", ['class' => 'checkbox']) ?>
    </div>
    <div class="col-md-3">
        <?= Html::checkbox("search-detail", false, ['id' => 'search-name', 'data-toggle' => 'checkbox']) ?>
        <?= Html::label("ファイル説明", "search-detail", ['class' => 'checkbox']) ?>
    </div>

and in JS file I call:

    $("input:checkbox").radioCheck();

But when I click on the checkbox ,It can not work ,clicked but checkbox state not change

Following are include js files :

[![enter image description here][1]][1]

  [1]: http://i.stack.imgur.com/4wvW1.png

Please tell me what wrong?
Thanks

**Comment by StefanYohansson** [comment]
You need to call:
```
$("input:checkbox").radiocheck();
```

without "C" capitalize.
