### ISSUE TITLE
typeahead + tagsinput

### ISSUE THREAD

**Issue by DogNick** [designmodo/Flat-UI#220]
i was trying to use this twitter typeahead (by bloodhound) in Flat-ui 's tagsinput but it doesn't work

would you please shed some light?

**Comment by StefanYohansson** [comment]
what's your typeahead version?

current typeahead support is: 
`"typeahead.js": "~0.10.5"`

You can find how to use section or examples here:

https://github.com/designmodo/Flat-UI/blob/master/docs/components.html
https://github.com/designmodo/Flat-UI/blob/master/docs/examples/tagsinput.html

**Comment by DogNick** [comment]
Many thanks
