### ISSUE TITLE
Feature: Make search input in navbar responsive and longer

### ISSUE THREAD

**Issue by drixie** [designmodo/Flat-UI#223]
This is more about my limited knowledge of CSS.

I am trying to make the search input in the navbar longer, and responsive. The current size is too small for my need, and I have been trying to make it longer with no success. Looking at the CSS, I can see the width is hard-coded at <200px. I have tried various values and even percentages with no success. 

Any advice will be appreciated, and it will be great if the search input is made responsive as a feature. 

Thanks!

**Comment by StefanYohansson** [comment]
I think it's a problem in the way you wrote your html.

```html
<div class="col-lg-12 col-md-12">
  <div class="form-group">
    <div class="input-group">
      <input type="text" class="form-control" placeholder="Search" id="search-query-3">
        <span class="input-group-btn">
          <button type="submit" class="btn"><span class="fui-search"></span></button>
        </span>
      </div>
    </div>
  </div>
```
