### ISSUE TITLE
Select box tab through and arrow keys don't move through options

### ISSUE THREAD

**Issue by phocks** [designmodo/Flat-UI#226]
I've tried on my own test and also on other sites like http://designmodo.github.io/Flat-UI/

Both tab and arrows don't seem to work to select options. Just wondering if this has just not been implemented yet or?

**Comment by StefanYohansson** [comment]
It's really odd.
I've checked if it's fault of [select2 v3.5.3](http://select2.github.io/select2/) but documentation arrows key works fine there.
I will search more about it in Flat-UI code.
