### ISSUE TITLE
Most of the components doesn't work

### ISSUE THREAD

**Issue by sahilshekhawat** [designmodo/Flat-UI#227]
I included all the files from `dist/`. Buttons and navbar seems to work fine but other than that, nothing works. Select, dropdown just doesn't work. Can someone help me out.

Also, radio button and checkboxes require a js plugin, it doesn't say how to download and use it in your project.

**Comment by StefanYohansson** [comment]
This is really odd, Demo uses dist folder and it's working.

can you take a look on Demo html and see what's missing in yours: http://designmodo.github.io/Flat-UI/

about radio/cehckbox this is the js file:
https://github.com/designmodo/Flat-UI/blob/b26fb47708e83b1d5427b70a5e0d076cdaa38431/js/radiocheck.js
