### ISSUE TITLE
Unable to override Bootstrap for my Rails app with Flat-UI free

### ISSUE THREAD

**Issue by indrekvainu** [designmodo/Flat-UI#230]
Hi, using the Flat-UI free version (looks awesome btw :)

I have trouble overriding the bootstrap design with it. Even though copying the flat-ui.css into stylesheets and using <link href="flat-ui.css" rel="stylesheet"> in my application.html.erb <head> I'm getting buttons that on hover look like this (they inherit something from Bootstrap and something from Flat UI but not just Flat UI which is the way I would want it).

![1](https://cloud.githubusercontent.com/assets/4834418/19571513/11196094-9707-11e6-9d6e-9b93115c8820.png)

Read the installation guide and browsed through stackoverflow, perhaps you can help. I'm a beginner so there might be something basic I'm missing. Help appreciated, keep up the good work!

**Comment by StefanYohansson** [comment]
Hi @indrekvainu ,

I am trying to reproduce your problem. 
https://gist.github.com/StefanYohansson/e888b330e89dc4a185d3de1a3895e93a
I just use bootstrap cdn and copy flat-ui css below bootstrap import. It's working here.

maybe your css import order ? you need to use
- bootstrap
- flat-ui

can you send some example?

**Comment by indrekvainu** [comment]
Hi, thank you for the reply, sorry it took a bit long to respond

What I currently have in my Rails app is in the application.html.erb the code in the beginning:

`<!DOCTYPE html>
<html>
<head>
  <title>Mapper</title>

 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>`

In my app/assets/stylesheets folder i have (in that order) application.css, bootstrap.css, contacts.css.scss, flat-ui.css, pages.css,scss, scaffolds.css.scss

Should I modify the application.html.erb file or modify the stylesheets? Not sure how exactly the flat-ui code should be placed and where to override bootstrap.

**Comment by StefanYohansson** [comment]
Hi @indrekvainu 

I don't know much about Rails, but what I read here: http://apidock.com/rails/ActionView/Helpers/AssetTagHelper/stylesheet_link_tag
and here:
http://stackoverflow.com/questions/15805810/stylesheet-link-tag-all-versus-media-all

your line:
`<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>`
will include your application.css, this way you will need to duplicate this line on application.html.erb and change that "application" for every css in your folder.
Or use sass to include css there.

using Rails thing, you can do something like:

```
// application.html.erb
<%= stylesheet_link_tag 'bootstrap', media: 'all', 'data-turbolinks-track' => true %>
<%= stylesheet_link_tag 'flat-ui', media: 'all', 'data-turbolinks-track' => true %>
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
```

or if you prefer use sass, you can change your `application.css` extension to `application.scss` or `application.sass` and use something like this

```
// application.scss
@import 'bootstrap';
@import 'flat-ui';
```

**Comment by indrekvainu** [comment]
Managed to solve it. Added in application.html.erb the following code only 

`<head>
  <title>Mapper</title>

 <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<%= stylesheet_link_tag    'flat-ui', media: 'all', 'data-turbolinks-track' => true %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>`

also in config/initializers/assets.rb added 'Rails.application.config.assets.precompile += %w( flat-ui.css )'

now the flat ui overrides bootstrap and is working. thanks.
