### ISSUE TITLE
Bootstrap 4 compatibility?

### ISSUE THREAD

**Issue by silentjay** [designmodo/Flat-UI#234]
Any idea if Flat-UI plays well with Bootstrap 4?

**Comment by maracuja-juice** [comment]
Haven't tried it out myself. But I think that it could do some weird things here and there.

**Comment by maracuja-juice** [comment]
Let me know how it goes. I would like to update to Bootstrap 4 aswell but this library here isn't maintained much anymore.

**Comment by StefanYohansson** [comment]
Maintain Flat UI is a huge job, you'll need to review every component not to mention that anytime you will need to review javascript dependencies too.

I contributed to other projects but as a theme Flat UI (that I tried to maintain) has a lot of people that ask/request but is not willing to help in any way.

@maracuja-juice since I refused my commit/merge rights, I don't know if anyone is available (I mean, have the time) to merge or review PRs here for the moment.

**Comment by maracuja-juice** [comment]
Thanks for your answer. This makes me more confident in contributing to this library. Will do!

**Comment by StefanYohansson** [comment]
I can't because I am not from designmodo (group or idk what designmodo is) and idk how it is bundled or where is hosted the paid version, I just do a small help here and there.

**Comment by xxxifan** [comment]
you guys may open a new project for continious migration

**Comment by maracuja-juice** [comment]
Does anyone know how much has to be done to migrate this to bootstrap 4?
I'm currently thinking about that because I really like the look but would like to use it with bootstrap 4. (+ building react components out of it)

**Comment by foria** [comment]
Hi Maurice

We’re on it.
At moment we are in the bug fixing and documentation updating phase.

Best,


▼▼
Marco Melluso
marcomelluso.com

**Comment by maracuja-juice** [comment]
Ah wow. Cool! @foria 
Is there a public repo yet?

**Comment by foria** [comment]
Soon, after updating job is over.


▼▼
Marco Melluso
marcomelluso.com

**Comment by maracuja-juice** [comment]
@foria Keep us updated. Sounds good!

**Comment by maracuja-juice** [comment]
So if I saw that correctly, there's now bootstrap 4 support? @foria

**Comment by foria** [comment]
Yes


▼▼
Marco Melluso
marcomelluso.com

**Comment by maracuja-juice** [comment]
@foria Great. The docs don't seem to be updated though. At least it still says on the `Getting started` page that you use version 3.
It also isn't released to GitHub.
Also I would like to know what else changed? Do you have a migration guide?
