### ISSUE TITLE
lato webfont

### ISSUE THREAD

**Issue by DanielRuf** [designmodo/Flat-UI#235]
We need an update or the files from https://github.com/betsol/lato-font and we can remoe old font files, see https://github.com/betsol/lato-font/issues/7

**Comment by DanielRuf** [comment]
Why was this closed? I see no changes in https://github.com/designmodo/Flat-UI/tree/master/dist/fonts/lato

**Comment by maracuja-juice** [comment]
Good question. Seems like all issues were closed before the Bootstrap 4 update: Maybe consider to open a new one.
