### ISSUE TITLE
Bootstrap 4 and SCSS compatibility

### ISSUE THREAD

**Issue by JordanGS** [designmodo/Flat-UI#236]
It would be great to see this project move forward to use Bootstrap 4 since 3 is no longer maintained and also when doing

`npm install flat-ui--save`

it would be great to have an scss variant which can be used.

`npm install flat-ui-scss --save`

**Comment by maracuja-juice** [comment]
See #234

**Comment by Designmodocom** [comment]
Hi guys, we have updated the Flat UI to Bootstrap 4. Please download the new version now.
