### ISSUE TITLE
Publish npm version 2.3.0

### ISSUE THREAD

**Issue by Dovakeidy** [designmodo/Flat-UI#248]
Currently, last version hosted in the npm registery is 2.1.1, please publish version 2.3.0

**Comment by maracuja-juice** [comment]
@StefanYohansson Do you know who can update that?

**Comment by defeated** [comment]
@Dovakeidy @maracuja-juice @StefanYohansson oddly there's another npm package `designmodo-flat-ui` that is at version `2.3.0` (published 2-years ago?)

https://www.npmjs.com/package/designmodo-flat-ui

The following worked for me:

```bash
$ yarn add designmodo-flat-ui --ignore-engines
```

```es6
import 'designmodo-flat-ui/dist/css/flat-ui.min.css';
```
