### ISSUE TITLE
I have some issue with implementing Bootstrap "Nav Menu Responsive Brand Logo" on flatui

### ISSUE THREAD

**Issue by stealthAngel** [designmodo/Flat-UI#249]
https://jsfiddle.net/w1cov1rv/1/

when I use flatui.css the whole "navbar-toggle collapsed" is misplaced, but when I remove flatui.css _External resources left panel from jsfiddle_ you'll see that the "navbar-toggle collapsed" is in the right place. 

I wonder what the solution for this is, maybe disabling flatui for the specific navbar?

I got the code from https://codepen.io/bootstrapped/pen/KwYGwq

**Comment by maracuja-juice** [comment]
What is your expected look / position?
Is it like this: 
![image](https://user-images.githubusercontent.com/16801528/34214475-e446b792-e5a2-11e7-9e32-b84638b871f6.png)
?

**Comment by stealthAngel** [comment]
This https://imgur.com/a/rmBK3 only with the blue color of flat ui

**Comment by maracuja-juice** [comment]
So that's what you need:
![image](https://user-images.githubusercontent.com/16801528/34244954-18068ad2-e628-11e7-9552-c3881b6c415e.png)

Here's the updated JsFiddle:
https://jsfiddle.net/w1cov1rv/3/

**Comment by stealthAngel** [comment]
Thank you for your reply sir.

The script works on jsfiddle but not on a html/php or blade file.

Download the file here and open the html page to see it for youself https://ufile.io/iuaes

I hope this can be fixed.

**Comment by maracuja-juice** [comment]
It doesn't seem like you updated your custom CSS with the corresponding changes I made in the JSFiddle.
You should specifically update this part of your CSS to this updated version:

    .example3 .navbar-toggle {
            /*padding: 10px;*/ /* remove this! */
            margin-top: 15px; /* you can of course also use the short hand version of margin again, if you want */
            margin-right: 15px;
            margin-bottom: 25px
    }

I removed the padding + changed margin-top to 15px instead of 25px.

**Comment by stealthAngel** [comment]
Sir you are awesome :) It's not perfect like plain bootstrap but it's good enough. Thank you 🗡
