### ISSUE TITLE
Update Documentation for Bootstrap 4

### ISSUE THREAD

**Issue by maracuja-juice** [designmodo/Flat-UI#251]
Your documentation wasn't updated for the new Bootstrap 4 changes. It would also be nice to have a migration guide. Thanks!

**Comment by sim2github** [comment]
+1 `gh-pages` - still `Bootstrap v3.2.0`
http://designmodo.github.io/Flat-UI/dist/css/vendor/bootstrap/css/bootstrap.min.css

**Comment by Designmodocom** [comment]
We have updated the demo page for Bootstrap 4. Please check.

**Comment by maracuja-juice** [comment]
1. The examples are not on GH Pages
2. How can we migrate?
